# https://github.com/dropseed/changerelease
# TODO: Investigate workflow running twice when releasing using git-flow methodology

name: changerelease
on:
  workflow_dispatch:
  push:
    paths: [CHANGELOG.md]
    branches: [main]
    tags: ["*"]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: dropseed/changerelease@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
