# https://github.com/marketplace/actions/close-action

name: close
on:
  pull_request:
    types: [closed]

jobs:
  build:
    name: Close
    runs-on: ubuntu-16.04
    steps:
      - uses: Logerfo/close-action@0.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment: true
